CREATE TABLE APICOLTORE
(
  ID_APICOLTORE INT PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL,
   
);

CREATE TABLE APIARIO (
    CODICE_APIARIO INT PRIMARY KEY,
    NUMERO_ARNIE INT NOT NULL,
    POSIZIONE VARCHAR(100) NOT NULL,
    COMUNE VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL,
    REGIONE VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_APICOLTORE) REFERENCES APICOLTORE(ID_APICOLTORE)
  
);

CREATE TABLE TIPOLOGIA (
    ID_TIPOLOGIA INT PRIMARY KEY,
    DESCRIZIONE VARCHAR(100) NOT NULL
    NOME_TIPOLOGIA VARCHAR(50) NOT NULL

);

CREATE TABLE MIELE (
    ID_MIELE INT PRIMARY KEY,
    DENOMINAZIONE VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_TIPOLOGIA) REFERENCES TIPOLOGIA(ID_TIPOLOGIA)

);

CREATE TABLE PRODUZIONE (
    ID_PRODUZIONE INT PRIMARY KEY,
    ANNO INT NOT NULL,
    QUANTITA FOAT NOT NULL,
    FOREIGN KEY (CODICE_APIARIO) REFERENCES APIARIO(CODICE_APIARIO),
    FOREIGN KEY (ID_MIELE) REFERENCES MIELE(ID_MIELE)

);

INSERT INTO APICOLTORE (ID_APICOLTORE, NOME) VALUES (1, 'Mario Rossi');
INSERT INTO APIARIO (CODICE_APIARIO, NUMERO_ARNIE, POSIZIONE, COMUNE, PROVINCIA, REGIONE, ID_APICOLTORE) VALUES (101, 50, 'Via delle Api 10', 'Firenze', 'Firenze', 'Toscana', 1);
INSERT INTO TIPOLOGIA (ID_TIPOLOGIA, DESCRIZIONE, NOME_TIPOLOGIA) VALUES (1, 'Miele di acacia', 'Acacia');
INSERT INTO MIELE (ID_MIELE, DENOMINAZIONE, ID_TIPOLOGIA) VALUES (1, 'Miele di acacia biologico', 1);
INSERT INTO PRODUZIONE (ID_PRODUZIONE, ANNO, QUANTITA, CODICE_APIARIO, ID_MIELE) VALUES (1, 2023, 150.5, 101, 1);

SELECT * FROM APICOLTORE;
SELECT NOME FROM APICOLTORE WHERE ID_APICOLTORE = 1;
SELECT POSIZIONE FROM APIARIO WHERE REGIONE = 'lombardia';
SELECT CODICE_APIARIO, NUMERO_ARNIE FROM APIARIO WHERE NUMERO_ARNIE > 10;
SELECT CODICE_APIARIO, POSIZIONE FROM APIARIO WHERE ID_APICOLTORE = 2;
SELECT DENOMINAZIONE FROM MIELE WHERE ID_MIELE = 5;
SELECT * FROM PRODUZIONE WHERE ANNO = 2024;
SELECT * FROM PRODUZIONE WHERE CODICE_APIARIO = A001;
SELECT PRODUZIONE WHERE ID_MIELE = 3 AND ANNO = 2023;