-- database: /path/to/database.db
CREATE TABLE APICOLTORE
(
  ID_APICOLTORE INT PRIMARY KEY,
  NOME VARCHAR(50) NOT NULL
);

CREATE TABLE APIARIO (
    CODICE_APIARIO INT PRIMARY KEY,
    NUMERO_ARNIE INT NOT NULL,
    POSIZIONE VARCHAR(100) NOT NULL,
    COMUNE VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL,
    REGIONE VARCHAR(50) NOT NULL,
    ID_APICOLTORE INT NOT NULL,
    FOREIGN KEY (ID_APICOLTORE) REFERENCES APICOLTORE(ID_APICOLTORE)
  
);

CREATE TABLE TIPOLOGIA (
    ID_TIPOLOGIA INT PRIMARY KEY,
    DESCRIZIONE VARCHAR(100) NOT NULL,
    NOME_TIPOLOGIA VARCHAR(50) NOT NULL

);

CREATE TABLE MIELE (
    ID_MIELE INT PRIMARY KEY,
    DENOMINAZIONE VARCHAR(50) NOT NULL,
    ID_TIPOLOGIA INT NOT NULL,
    FOREIGN KEY (ID_TIPOLOGIA) REFERENCES TIPOLOGIA(ID_TIPOLOGIA)

);

CREATE TABLE PRODUZIONE (
    ID_PRODUZIONE INT PRIMARY KEY,
    ANNO INT NOT NULL,
    QUANTITA FOAT NOT NULL,
    CODICE_APIARIO INT NOT NULL,
    ID_MIELE INT NOT NULL, --bisogna mettere questa riga in ogni foreign key
    FOREIGN KEY (CODICE_APIARIO) REFERENCES APIARIO(CODICE_APIARIO),
    FOREIGN KEY (ID_MIELE) REFERENCES MIELE(ID_MIELE)

);

INSERT INTO APICOLTORE (ID_APICOLTORE, NOME) VALUES (1, 'Mario Rossi');
INSERT INTO APIARIO (CODICE_APIARIO, NUMERO_ARNIE, POSIZIONE, COMUNE, PROVINCIA, REGIONE, ID_APICOLTORE) VALUES (101, 50, 'Via delle Api 10', 'Firenze', 'Firenze', 'Toscana', 1);
INSERT INTO TIPOLOGIA (ID_TIPOLOGIA, DESCRIZIONE, NOME_TIPOLOGIA) VALUES (1, 'Miele di acacia', 'Acacia');
INSERT INTO MIELE (ID_MIELE, DENOMINAZIONE, ID_TIPOLOGIA) VALUES (1, 'Miele di acacia biologico', 1);
INSERT INTO PRODUZIONE (ID_PRODUZIONE, ANNO, QUANTITA, CODICE_APIARIO, ID_MIELE) VALUES (1, 2023, 150.5, 101, 1);

SELECT * FROM APICOLTORE;
SELECT NOME FROM APICOLTORE WHERE ID_APICOLTORE = 1;
SELECT POSIZIONE FROM APIARIO WHERE REGIONE = 'lombardia';
SELECT CODICE_APIARIO, NUMERO_ARNIE FROM APIARIO WHERE NUMERO_ARNIE > 10;
SELECT CODICE_APIARIO, POSIZIONE FROM APIARIO WHERE ID_APICOLTORE = 2;
SELECT DENOMINAZIONE FROM MIELE WHERE ID_MIELE = 5;
SELECT * FROM PRODUZIONE WHERE ANNO = 2024;
SELECT * FROM PRODUZIONE WHERE CODICE_APIARIO = 001;
SELECT PRODUZIONE WHERE ID_MIELE = 3 AND ANNO = 2023;

--  Quantità totale prodotta per anno
SELECT ANNO, SUM(QUANTITA) AS QUANTITA_TOTALE 
FROM PRODUZIONE 
GROUP BY ANNO;
-- Spiegazione: raggruppa per anno e somma tutte le quantità di quell'anno

--  Produzione media per apiario  
SELECT CODICE_APIARIO, AVG(QUANTITA) AS MEDIA_PRODUZIONE 
FROM PRODUZIONE 
GROUP BY CODICE_APIARIO;
-- Spiegazione: raggruppa per apiario e calcola la media delle quantità prodotte

--  Numero di produzioni e produzione totale per miele
SELECT ID_MIELE, COUNT(*) AS NUMERO_PRODUZIONI, SUM(QUANTITA) AS PRODUZIONE_TOTALE 
FROM PRODUZIONE 
GROUP BY ID_MIELE;
-- Spiegazione: raggruppa per tipo di miele, conta quante volte è stato prodotto e somma le quantità

--  Produzione totale per miele nell'anno 2024
SELECT ID_MIELE, SUM(QUANTITA) AS PRODUZIONE_TOTALE 
FROM PRODUZIONE 
WHERE ANNO = 2024 
GROUP BY ID_MIELE;
-- Spiegazione: filtra solo anno 2024, poi raggruppa per miele e somma quantità

--  Valore massimo e minimo di produzione per anno
SELECT ANNO, MAX(QUANTITA) AS VALORE_MAX, MIN(QUANTITA) AS VALORE_MIN 
FROM PRODUZIONE 
GROUP BY ANNO;
-- Spiegazione: raggruppa per anno, trova il valore più alto e più basso

--  Numero di mieli per tipologia
SELECT ID_TIPOLOGIA, COUNT(*) AS NUMERO_MIELI 
FROM MIELE 
GROUP BY ID_TIPOLOGIA;
-- Spiegazione: raggruppa per tipologia e conta quanti mieli ci sono per ogni tipologia

--  Conteggio produzioni con quantità > 100 per anno
SELECT ANNO, COUNT(*) AS NUMERO_PRODUZIONI 
FROM PRODUZIONE 
WHERE QUANTITA > 100 
GROUP BY ANNO;
-- Spiegazione: filtra solo quantità > 100, raggruppa per anno e conta

--  Somma quantità per miele e anno
SELECT ID_MIELE, ANNO, SUM(QUANTITA) AS SOMMA_QUANTITA 
FROM PRODUZIONE 
GROUP BY ID_MIELE, ANNO;
-- Spiegazione: raggruppa per miele E anno insieme, somma le quantità